In [1]:
import pandas as pd

In [2]:
data_path= 'Resources/Petroleum_Well.csv'
wells_df=pd.read_csv(data_path)

In [3]:
#Converting csv file into Data Frame
wells_df=pd.DataFrame(wells_df).copy()
wells_df.head()

,X,Y,OBJECTID,OGF_ID,WELL_ID,LICENCE_NUMBER,WELL_NAME,OPERATOR,WELL_TYPE,WELL_MODE,...,DEEPENING_FLG,REENTRY_FLG,LATERAL_FLG,SPUD_DATE,TOTAL_DEPTH_REACHED_DATE,PLUGGING_END_DATE,MAP_SYMBOL_CODE,GEOMETRY_UPDATE_DATETIME,EFFECTIVE_DATETIME,SYSTEM_DATETIME
0,-80.218198,43.133536,130116593,244130641,32702,F020287,Bow Park Farm Well #9,Bow Park Farms,Natural Gas Well,Unknown,...,N,N,N,1904/01/01 00:00:00+00,1904/01/01 00:00:00+00,1970/01/01 00:00:00+00,GP - UNK,2020/09/23 14:27:56+00,2020/09/23 14:27:56+00,2020/09/23 14:27:56+00
1,-80.206309,43.121120,130116609,244130642,32703,F020288,Bow Park Farm Well #3,Bow Park Farms,Natural Gas Well,Unknown,...,N,N,N,1904/01/01 00:00:00+00,1904/01/01 00:00:00+00,1970/01/01 00:00:00+00,GP - UNK,2020/09/23 14:27:56+00,2020/09/23 14:27:56+00,2020/09/23 14:27:56+00
2,-80.213643,43.113897,130116625,244130643,32704,F020289,Bow Park Farm Well #6,Bow Park Farms,Natural Gas Well,Unknown,...,N,N,N,1904/01/01 00:00:00+00,1904/01/01 00:00:00+00,1970/01/01 00:00:00+00,GP - UNK,2020/09/23 14:27:56+00,2020/09/23 14:27:56+00,2020/09/23 14:27:56+00
3,-80.337281,43.177397,130116641,244130644,32705,F020290,Brant Hydro Station,Unknown,Dry Hole,Unknown,...,N,N,N,1800/01/01 00:00:00+00,1800/01/01 00:00:00+00,1970/01/01 00:00:00+00,DH - UNK,2020/09/23 14:27:56+00,2020/09/23 14:27:56+00,2020/09/23 14:27:56+00
4,-80.209004,43.133897,130116657,244130645,32706,F020291,Bow Park Well #7,Bow Park Farms,Gas Show,Unknown,...,N,N,N,1800/01/01 00:00:00+00,1800/01/01 00:00:00+00,1970/01/01 00:00:00+00,GS - UNK,2020/09/23 14:27:56+00,2020/09/23 14:27:56+00,2020/09/23 14:27:56+00

In [4]:
#geting unique values fo well_mode and creating a Data Frame with them
well_mode= wells_df['WELL_MODE'].unique()
cat_well_mode=pd.DataFrame(well_mode)
cat_well_mode.columns=['CAT well mode']

In [5]:
cat_well_mode.head()

    CAT well mode
0         Unknown
1  Abandoned Well
2  Suspended Well
3     Active Well
4     Capped Well

In [6]:
wells_df['OPERATOR']=wells_df['OPERATOR'].str.upper()

In [7]:
operator= wells_df['OPERATOR'].unique()
cat_operator=pd.DataFrame(operator)
cat_operator.columns=['Operator']

In [8]:
#sorting values 
cat_operator = cat_operator.sort_values(['Operator'])
cat_operator.reset_index(drop=True, inplace=True)

In [9]:
#exporting dfs to csv files
cat_well_mode.to_csv(r'Resources/cat_well_mode.csv', index=False)
cat_operator.to_csv(r'Resources/cat_operator.csv', index=False)